### ISSUE TITLE
Unmet dependencies for the package

### ISSUE THREAD

**Issue by ipa-rar** [hsd-dev/rosgraph_monitor-backup#10]
branch:  nav_observer 
Process failed with `ImportError: cannot import name GetROSModel` while launching `demo.launch`
`rosbridge_websocket.launch` failed with `BSON installation does not support all necessary features`

Is it possible to dockerize it??@ipa-hsd

**Comment by hsd-dev** [comment]
I think the issue is solved @ipa-rar. Please reopen if not.
